# Generated by Django 5.1.7 on 2025-03-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_announcement_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_approved',
        ),
    ]
