# Generated by Django 5.1.7 on 2025-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
