# Generated by Django 5.1.7 on 2025-04-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_announcement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='fkko_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ФККО'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement_new', 'Новое объявление'), ('announcement_reported', 'Жалоба на объявление'), ('user_registered', 'Новый пользователь'), ('payment_received', 'Получен платеж'), ('announcement_approved', 'Объявление одобрено'), ('announcement_rejected', 'Объявление отклонено')], max_length=50),
        ),
    ]
