# Generated by Django 5.1.7 on 2025-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_announcement_fkko_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsdummy',
            options={'verbose_name': 'Аналитика', 'verbose_name_plural': 'Аналитика'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='announcementimage',
            options={'verbose_name': 'Изображение объявления', 'verbose_name_plural': 'Изображения объявлений'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение в галерее', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='otherannouncement',
            options={'verbose_name': 'Другое объявление', 'verbose_name_plural': 'Другие объявления'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Тарифный план', 'verbose_name_plural': 'Тарифные планы'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('archived', 'Архивировано')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement_new', 'Новое объявление'), ('announcement_reported', 'Жалоба на объявление'), ('user_registered', 'Новый пользователь'), ('payment_received', 'Получен платёж'), ('announcement_approved', 'Объявление одобрено'), ('announcement_rejected', 'Объявление отклонено')], max_length=50),
        ),
    ]
