# Generated by Django 5.1.7 on 2025-05-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_analyticsdummy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='fkko_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Код ФККО (через запятую)'),
        ),
    ]
