# Generated by Django 5.1.7 on 2026-01-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
